version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: pet_app2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: pet_app2
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  flyway:
    image: flyway/flyway:9.22.1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/pet_app2
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: "123"
      FLYWAY_CONNECT_RETRIES: 10
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    command: migrate

volumes:
  postgres_data: